test: 
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID:     ASrkt1KpPSpyOiR0zYMWcQO9sBdRSPlpPq5JSQjVS7CV1wr_oETkuwdEoeFY7Ydkz8S9KNeesb-2hPfj
  PAYPAL_CLIENT_SECRET:   EGPgK8Mvsa7UQw40JaQ7zCymtDLqXJVCL35LkcH6XH6uHLuEBcBLb52GY_TroCnX6o2HuyMR3_MnXmMJ
  STRIPE_PUBLISHABLE_KEY: YOUR_CREDENTIAL_HERE
  STRIPE_SECRET_KEY:  YOUR_CREDENTIAL_HERE

development:
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID:     ASrkt1KpPSpyOiR0zYMWcQO9sBdRSPlpPq5JSQjVS7CV1wr_oETkuwdEoeFY7Ydkz8S9KNeesb-2hPfj
  PAYPAL_CLIENT_SECRET:   EGPgK8Mvsa7UQw40JaQ7zCymtDLqXJVCL35LkcH6XH6uHLuEBcBLb52GY_TroCnX6o2HuyMR3_MnXmMJ
  STRIPE_PUBLISHABLE_KEY: YOUR_CREDENTIAL_HERE
  STRIPE_SECRET_KEY:  YOUR_CREDENTIAL_HERE