name: Action Workflow

#on: [push]
on: pull_request

env: 
  WF_ENV: Available to all jobs

#on: 
#  repository_dispatch:
#    types: [build]
#push:
#pull_request:
#  types: [closed, assigned, opened, reopened]
#on:
#  pull_request:
#    branches:
#      -master

jobs:
  run-github-Action:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in run-github-Action job
    steps:
      - name: list before commit
        env:
          STEPS_ENV: Available only to this step
        run: |
          ls -a
          pwd
          #echo $GITHUB_SHA
          #echo $GITHUB_REPOSITORY
          #echo $GITHUB_WORKSPACE
          #echo ${{ github.token }}
      - name: checkout files from repo
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PAT }}
          repository: tasahmed/shoppingCartBasic
      - name: list script after checkout
        run : |
          ls -a
          pwd
      - name: Simple js Action
        id: sjsa
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Taslim
      - name: Log greeting time
        run: echo "${{ steps.sjsa.output.time }}"
      - name: check enviroment varaible
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEPS_ENV ${STEPS_ENV}"