name: Action Workflow

on: [push]

jobs:
  run-github-Action:
    runs-on: ubuntu-latest
    steps:
      - name: list scirpt before checkout
        run: |
          ls -a
          pwd
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: list script after checkout
        run : |
          ls -a
          pwd
      - name: Simple js Action
        id: sjsa
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Taslim
      - name: Log greeting time
        run: echo "${{ steps.sjsa.output.time }}"